import type { SeasonSummaryRow } from '../../data/generated/asset-types';
import { ALL_DYNASTY_TEAMS, type DynastyMode, type DynastyState } from './dynasty-types.ts';
export { ALL_DYNASTY_TEAMS };

const finite = (value: unknown): number | null => { const n = Number(value); return Number.isFinite(n) ? n : null; };
export function availableDynastySeasons(rows: readonly Pick<SeasonSummaryRow, 'season'>[]): number[] { return [...new Set(rows.map(row => row.season).filter(Number.isFinite))].sort((a, b) => a - b); }
export function availableDynastyOwners(rows: readonly Pick<SeasonSummaryRow, 'owner'>[]): string[] { return [...new Set(rows.map(row => row.owner).filter(Boolean))].sort((a, b) => a.localeCompare(b)); }
export function normalizeDynastyRange(input: { availableSeasons: readonly number[]; startSeason?: unknown; endSeason?: unknown; requestedStartSeason?: unknown; requestedEndSeason?: unknown; windowSize?: number }): Pick<DynastyState, 'startSeason' | 'endSeason' | 'requestedStartSeason' | 'requestedEndSeason'> {
  const seasons = [...input.availableSeasons].filter(Number.isFinite).sort((a, b) => a - b); const latestStart = seasons[Math.max(0, seasons.length - (input.windowSize || 3))] ?? null; const defaultEnd = seasons.at(-1) ?? null;
  const requestedStart = finite(input.requestedStartSeason) ?? finite(input.startSeason) ?? latestStart; const requestedEnd = finite(input.requestedEndSeason) ?? finite(input.endSeason) ?? defaultEnd;
  if (requestedStart === null || requestedEnd === null || !seasons.length) return { requestedStartSeason: requestedStart, requestedEndSeason: requestedEnd, startSeason: null, endSeason: null };
  const min = seasons[0], max = seasons.at(-1)!; const start = Math.min(Math.max(requestedStart, min), max); const end = Math.min(Math.max(requestedEnd, min), max);
  return { requestedStartSeason: requestedStart, requestedEndSeason: requestedEnd, startSeason: Math.min(start, end), endSeason: Math.max(start, end) };
}
export function resolveDynastyInitialState(input: { seasonSummaries: readonly SeasonSummaryRow[]; urlState?: { dynastyMode?: string | null; dynastyOwner?: string | null; dynastyStart?: number | null; dynastyEnd?: number | null; dynastyMinSeasons?: number | null; dynastySaunders?: boolean | null }; mode?: DynastyMode; owner?: string | null; startSeason?: number | null; endSeason?: number | null; minSeasons?: number; includeSaundersPenalty?: boolean }): DynastyState {
  const seasons = availableDynastySeasons(input.seasonSummaries); const owners = availableDynastyOwners(input.seasonSummaries); const url = input.urlState || {}; const requestedMode = (url.dynastyMode || input.mode || 'all-time') as DynastyMode; const selectedOwner = requestedMode === 'calculator' ? ((url.dynastyOwner || input.owner || owners[0]) && owners.includes(url.dynastyOwner || input.owner || '') ? (url.dynastyOwner || input.owner || owners[0]) : owners[0] || ALL_DYNASTY_TEAMS) : ALL_DYNASTY_TEAMS; const range = normalizeDynastyRange({ availableSeasons: seasons, startSeason: input.startSeason, endSeason: input.endSeason, requestedStartSeason: url.dynastyStart ?? input.startSeason, requestedEndSeason: url.dynastyEnd ?? input.endSeason }); const fallback = normalizeDynastyRange({ availableSeasons: seasons }); return { mode: requestedMode, owner: selectedOwner || ALL_DYNASTY_TEAMS, startSeason: range.startSeason ?? fallback.startSeason, endSeason: range.endSeason ?? fallback.endSeason, requestedStartSeason: range.requestedStartSeason ?? fallback.requestedStartSeason, requestedEndSeason: range.requestedEndSeason ?? fallback.requestedEndSeason, minSeasons: Math.max(1, Number(url.dynastyMinSeasons ?? input.minSeasons ?? 2)), includeSaundersPenalty: url.dynastySaunders ?? input.includeSaundersPenalty ?? true, chartHiddenOwners: [], selectedWindowKey: null, selectedWindowKind: null };
}
