#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');
const standaloneCode = require('ajv/dist/standalone').default;
const esbuild = require('esbuild');
const { GENERATED_ASSETS } = require('./data/constants.cjs');
const { createAjv, schemaId } = require('./data/schema-validation.cjs');

function outputRootFromArgs(argv) {
  const index = argv.indexOf('--output-root');
  return index >= 0 ? path.resolve(argv[index + 1]) : process.cwd();
}

function specializeFormatRuntime(standaloneModule) {
  const specialized = standaloneModule.replaceAll(
    'require("ajv-formats/dist/formats")',
    'require("./scripts/data/standalone-formats.cjs")',
  );
  if (specialized.includes('ajv-formats/dist/formats')) {
    throw new Error('Generated validators still reference the full ajv-formats runtime');
  }
  return specialized;
}

function compactValidatorErrors(standaloneModule) {
  const compacted = standaloneModule.replace(
    /,schemaPath:"(?:\\.|[^"])*",keyword:"[^"]+",params:\{(?:"(?:\\.|[^"])*"|[^{}])*\}/g,
    '',
  );
  if (compacted.includes('schemaPath:') || compacted.includes('keyword:') || compacted.includes('params:')) {
    throw new Error('Generated validators contain an unsupported error-object shape');
  }
  return compacted;
}

function generateAssetValidators({ sourceRoot = process.cwd(), outputRoot = sourceRoot } = {}) {
  const ajv = createAjv(sourceRoot, {
    loopEnum: 0,
    loopRequired: 0,
    messages: false,
    code: { esm: true, source: true, optimize: 3 },
  });
  const ajvStandaloneModule = standaloneCode(ajv, {
    validateH2H: schemaId('h2h.schema.json'),
    validateSeasonSummary: schemaId('season-summary.schema.json'),
    validateRivalries: schemaId('rivalries.schema.json'),
    validateCurrentSeason: schemaId('current-season.schema.json'),
    validateDraftSpot: schemaId('draft-spot.schema.json'),
    validateDerivedStats: schemaId('derived-stats.schema.json'),
    validateAssetManifest: schemaId('asset-manifest.schema.json'),
  });
  const standaloneModule = specializeFormatRuntime(compactValidatorErrors(ajvStandaloneModule));
  const moduleCode = esbuild.buildSync({
    stdin: {
      contents: standaloneModule,
      loader: 'js',
      resolveDir: sourceRoot,
      sourcefile: 'asset-validator-runtime.mjs',
    },
    bundle: true,
    platform: 'browser',
    format: 'esm',
    target: 'es2022',
    write: false,
    legalComments: 'none',
  }).outputFiles[0].text;
  const wrappers = `

import type { AssetManifest, CurrentSeasonData, DerivedStats, DraftSpot, H2HGame, RivalryDefinition, SeasonSummaryRow } from './asset-types';

export function isH2H(value: unknown): value is H2HGame[] { return validateH2H(value) as boolean; }
export function isSeasonSummary(value: unknown): value is SeasonSummaryRow[] { return validateSeasonSummary(value) as boolean; }
export function isRivalries(value: unknown): value is RivalryDefinition[] { return validateRivalries(value) as boolean; }
export function isCurrentSeason(value: unknown): value is CurrentSeasonData { return validateCurrentSeason(value) as boolean; }
export function isDraftSpot(value: unknown): value is DraftSpot { return validateDraftSpot(value) as boolean; }
export function isDerivedStats(value: unknown): value is DerivedStats { return validateDerivedStats(value) as boolean; }
export function isAssetManifest(value: unknown): value is AssetManifest { return validateAssetManifest(value) as boolean; }
export type ValidatorName = 'H2H' | 'SeasonSummary' | 'Rivalries' | 'CurrentSeason' | 'DraftSpot' | 'DerivedStats' | 'AssetManifest';
export function getValidatorErrors(name: ValidatorName): Array<{ instancePath?: string; message?: string }> | null {
  const validators = { H2H: validateH2H, SeasonSummary: validateSeasonSummary, Rivalries: validateRivalries, CurrentSeason: validateCurrentSeason, DraftSpot: validateDraftSpot, DerivedStats: validateDerivedStats, AssetManifest: validateAssetManifest };
  return (validators[name] as any).errors || null;
}

export function formatValidatorErrors(assetPath: string, errors: Array<{ instancePath?: string; message?: string }> | null | undefined): string {
  const error = errors?.[0];
  if (!error) return \`\${assetPath}: schema validation failed\`;
  const location = error.instancePath ? error.instancePath.replace(/^\\//, '').replaceAll('/', '.') : 'root';
  return \`\${assetPath}: field "\${location}": \${error.message || 'schema validation failed'}\`;
}
`;
  const outputPath = path.join(outputRoot, GENERATED_ASSETS.AssetValidators.path);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, `// This file is generated by scripts/generate_asset_validators.cjs. Do not edit manually.\n// @ts-nocheck\n${moduleCode.trim()}${wrappers}`);

  // LeagueLore is optional and must be safe to validate in the browser without
  // shipping the full AJV runtime. Keep this structural validator generated so
  // the loader and checked-in artifact cannot silently diverge.
  const loreOutputPath = path.join(outputRoot, 'src/data/generated/league-lore-validator.ts');
  const loreValidator = `
import type { LeagueLore } from './asset-types';
const O = (v: unknown): v is Record<string, any> => !!v && typeof v === 'object' && !Array.isArray(v);
const S = (v: unknown): v is string => typeof v === 'string' && v.length > 0;
const I = Number.isInteger;
const A = (v: unknown, p: (x: any) => boolean) => Array.isArray(v) && v.length > 0 && v.every(p);
const ID = (v: unknown) => S(v) && /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v);
const OWN = (v: unknown) => S(v);
const STRS = (v: unknown) => A(v, S);
const ANCHOR = (v: unknown): boolean => {
  if (!O(v) || !S(v.type)) return false;
  if (v.type === 'owner-season' || v.type === 'season') return OWN(v.owner) && I(v.season) || v.type === 'season' && I(v.season);
  if (v.type === 'game') return I(v.season) && I(v.week) && S(v.game_type) && Array.isArray(v.owners) && v.owners.length === 2 && v.owners.every(OWN);
  if (v.type === 'draft-slot') return I(v.season) && OWN(v.owner) && (v.expected_slot === undefined || I(v.expected_slot));
  if (v.type === 'draft-selection') return I(v.season) && OWN(v.owner) && S(v.player_id);
  if (v.type === 'transaction') return I(v.season) && S(v.transaction_id);
  if (v.type === 'record') return v.selector === 'lowest-score' && ANCHOR(v.game);
  if (v.type === 'rivalry') return Array.isArray(v.owners) && v.owners.length === 2 && v.owners.every(OWN) || S(v.slug);
  return false;
};
const ENTRY = (v: unknown) => O(v) && ID(v.id) && S(v.category) && S(v.title) && S(v.teaser) && STRS(v.body) && Array.isArray(v.owners) && v.owners.every(OWN) && Array.isArray(v.anchors) && v.anchors.every(ANCHOR) && STRS(v.search_terms) && S(v.provenance) && [v.season, v.occurred_year, v.completed_year, v.almanac_edition].every(x => x === null || I(x)) && ['ordinary', 'sensitive', 'respectful'].includes(v.sensitivity) && typeof v.enabled === 'boolean';
const TRIGGER = (v: unknown) => O(v) && ID(v.id) && S(v.surface) && S(v.activation) && S(v.once_policy) && typeof v.enabled === 'boolean' && (('entry_id' in v) !== ('collection_id' in v)) && (!('entry_id' in v) || ID(v.entry_id)) && (!('collection_id' in v) || ID(v.collection_id)) && (!('effect_id' in v) || ID(v.effect_id)) && (!('match' in v) || O(v.match));
const COLLECTION = (v: unknown) => O(v) && ID(v.id) && S(v.title) && S(v.summary) && STRS(v.entry_ids) && STRS(v.search_terms) && typeof v.enabled === 'boolean';
const EFFECT = (v: unknown) => O(v) && ID(v.id) && S(v.label) && S(v.symbol) && S(v.presentation) && S(v.tone) && I(v.duration_ms) && S(v.motion_policy) && typeof v.enabled === 'boolean';
export function isLeagueLore(value: unknown): value is LeagueLore {
  return O(value) && value.schema_version === 1 && typeof value.enabled === 'boolean' && S(value.updated_at) && O(value.source_policy) && STRS(value.source_policy.numeric_authority) && I(value.source_policy.almanac_narrative_through) && A(value.owners, item => O(item) && OWN(item.owner) && STRS(item.aliases)) && A(value.commissioner_terms, item => O(item) && ID(item.id) && OWN(item.owner) && I(item.term_start) && (item.term_end === null || I(item.term_end)) && S(item.display_term) && S(item.summary) && STRS(item.entry_ids)) && A(value.collections, COLLECTION) && A(value.effects, EFFECT) && Array.isArray(value.entries) && value.entries.every(ENTRY) && A(value.triggers, TRIGGER);
}
`;
  fs.mkdirSync(path.dirname(loreOutputPath), { recursive: true });
  fs.writeFileSync(loreOutputPath, `// This file is generated by scripts/generate_asset_validators.cjs. Do not edit manually.\n// @ts-nocheck\n${loreValidator.trim()}\n`);

  const transactionStandaloneModule = specializeFormatRuntime(compactValidatorErrors(standaloneCode(ajv, {
    validateTransactionHistory: schemaId('transaction-history.schema.json'),
  })));
  const transactionModuleCode = esbuild.buildSync({
    stdin: {
      contents: transactionStandaloneModule,
      loader: 'js',
      resolveDir: sourceRoot,
      sourcefile: 'transaction-history-validator-runtime.mjs',
    },
    bundle: true,
    platform: 'browser',
    format: 'esm',
    target: 'es2022',
    write: false,
    legalComments: 'none',
  }).outputFiles[0].text;
  const transactionWrappers = `

import type { TransactionHistory } from './asset-types';

export function isTransactionHistory(value: unknown): value is TransactionHistory { return validateTransactionHistory(value) as boolean; }
export function getTransactionHistoryValidatorErrors(): Array<{ instancePath?: string; message?: string }> | null {
  return (validateTransactionHistory as any).errors || null;
}
`;
  const transactionOutputPath = path.join(outputRoot, GENERATED_ASSETS.TransactionHistoryValidator.path);
  fs.mkdirSync(path.dirname(transactionOutputPath), { recursive: true });
  fs.writeFileSync(
    transactionOutputPath,
    `// This file is generated by scripts/generate_asset_validators.cjs. Do not edit manually.\n// @ts-nocheck\n${transactionModuleCode.trim()}${transactionWrappers}`,
  );
  return outputPath;
}

if (require.main === module) {
  try {
    const output = generateAssetValidators({ outputRoot: outputRootFromArgs(process.argv.slice(2)) });
    console.log(`Generated ${path.relative(process.cwd(), output)}`);
  } catch (error) {
    console.error(error.message || error);
    process.exit(1);
  }
}

module.exports = {
  generateAssetValidators,
  compactValidatorErrors,
  outputRootFromArgs,
  specializeFormatRuntime,
};
