#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');
const standaloneCode = require('ajv/dist/standalone').default;
const esbuild = require('esbuild');
const { GENERATED_ASSETS } = require('./data/constants.cjs');
const { createAjv, schemaId } = require('./data/schema-validation.cjs');

function outputRootFromArgs(argv) {
  const index = argv.indexOf('--output-root');
  return index >= 0 ? path.resolve(argv[index + 1]) : process.cwd();
}

function specializeFormatRuntime(standaloneModule) {
  const specialized = standaloneModule.replaceAll(
    'require("ajv-formats/dist/formats")',
    'require("./scripts/data/standalone-formats.cjs")',
  );
  if (specialized.includes('ajv-formats/dist/formats')) {
    throw new Error('Generated validators still reference the full ajv-formats runtime');
  }
  return specialized;
}

function compactValidatorErrors(standaloneModule) {
  const compacted = standaloneModule.replace(
    /,schemaPath:"(?:\\.|[^"])*",keyword:"[^"]+",params:\{(?:"(?:\\.|[^"])*"|[^{}])*\}/g,
    '',
  );
  if (compacted.includes('schemaPath:') || compacted.includes('keyword:') || compacted.includes('params:')) {
    throw new Error('Generated validators contain an unsupported error-object shape');
  }
  return compacted;
}

function generateAssetValidators({ sourceRoot = process.cwd(), outputRoot = sourceRoot } = {}) {
  const ajv = createAjv(sourceRoot, {
    loopEnum: 0,
    loopRequired: 0,
    messages: false,
    code: { esm: true, source: true, optimize: 3 },
  });
  const ajvStandaloneModule = standaloneCode(ajv, {
    validateH2H: schemaId('h2h.schema.json'),
    validateSeasonSummary: schemaId('season-summary.schema.json'),
    validateRivalries: schemaId('rivalries.schema.json'),
    validateCurrentSeason: schemaId('current-season.schema.json'),
    validateDraftSpot: schemaId('draft-spot.schema.json'),
    validateDerivedStats: schemaId('derived-stats.schema.json'),
    validateAssetManifest: schemaId('asset-manifest.schema.json'),
  });
  const standaloneModule = specializeFormatRuntime(compactValidatorErrors(ajvStandaloneModule));
  const moduleCode = esbuild.buildSync({
    stdin: {
      contents: standaloneModule,
      loader: 'js',
      resolveDir: sourceRoot,
      sourcefile: 'asset-validator-runtime.mjs',
    },
    bundle: true,
    platform: 'browser',
    format: 'esm',
    target: 'es2022',
    write: false,
    legalComments: 'none',
  }).outputFiles[0].text;
  const wrappers = `

import type { AssetManifest, CurrentSeasonData, DerivedStats, DraftSpot, H2HGame, RivalryDefinition, SeasonSummaryRow } from './asset-types';

export function isH2H(value: unknown): value is H2HGame[] { return validateH2H(value) as boolean; }
export function isSeasonSummary(value: unknown): value is SeasonSummaryRow[] { return validateSeasonSummary(value) as boolean; }
export function isRivalries(value: unknown): value is RivalryDefinition[] { return validateRivalries(value) as boolean; }
export function isCurrentSeason(value: unknown): value is CurrentSeasonData { return validateCurrentSeason(value) as boolean; }
export function isDraftSpot(value: unknown): value is DraftSpot { return validateDraftSpot(value) as boolean; }
export function isDerivedStats(value: unknown): value is DerivedStats { return validateDerivedStats(value) as boolean; }
export function isAssetManifest(value: unknown): value is AssetManifest { return validateAssetManifest(value) as boolean; }
export type ValidatorName = 'H2H' | 'SeasonSummary' | 'Rivalries' | 'CurrentSeason' | 'DraftSpot' | 'DerivedStats' | 'AssetManifest';
export function getValidatorErrors(name: ValidatorName): Array<{ instancePath?: string; message?: string }> | null {
  const validators = { H2H: validateH2H, SeasonSummary: validateSeasonSummary, Rivalries: validateRivalries, CurrentSeason: validateCurrentSeason, DraftSpot: validateDraftSpot, DerivedStats: validateDerivedStats, AssetManifest: validateAssetManifest };
  return (validators[name] as any).errors || null;
}

export function formatValidatorErrors(assetPath: string, errors: Array<{ instancePath?: string; message?: string }> | null | undefined): string {
  const error = errors?.[0];
  if (!error) return \`\${assetPath}: schema validation failed\`;
  const location = error.instancePath ? error.instancePath.replace(/^\\//, '').replaceAll('/', '.') : 'root';
  return \`\${assetPath}: field "\${location}": \${error.message || 'schema validation failed'}\`;
}
`;
  const outputPath = path.join(outputRoot, GENERATED_ASSETS.AssetValidators.path);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, `// This file is generated by scripts/generate_asset_validators.cjs. Do not edit manually.\n// @ts-nocheck\n${moduleCode.trim()}${wrappers}`);

  // LeagueLore is optional and must be safe to validate in the browser without
  // shipping the full AJV runtime. Keep this structural validator generated so
  // the loader and checked-in artifact cannot silently diverge.
  const loreOutputPath = path.join(outputRoot, 'src/data/generated/league-lore-validator.ts');
  const loreValidator = `
import type { LeagueLore } from './asset-types';
const object = (value: unknown): value is Record<string, any> => !!value && typeof value === 'object' && !Array.isArray(value);
const strings = (value: unknown) => Array.isArray(value) && value.every(item => typeof item === 'string' && item.length > 0);
const id = (value: unknown) => typeof value === 'string' && /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value);
const owner = (value: unknown) => typeof value === 'string' && value.length > 0;
const integer = (value: unknown) => Number.isInteger(value);
const arrayOf = (value: unknown, check: (item: unknown) => boolean) => Array.isArray(value) && value.every(check);
const anchor = (value: unknown): boolean => {
  if (!object(value) || typeof value.type !== 'string') return false;
  if (value.type === 'owner-season') return owner(value.owner) && integer(value.season);
  if (value.type === 'game') return integer(value.season) && integer(value.week) && typeof value.game_type === 'string' && Array.isArray(value.owners) && value.owners.length === 2 && value.owners.every(owner);
  if (value.type === 'draft-slot') return integer(value.season) && owner(value.owner) && (value.expected_slot === undefined || integer(value.expected_slot));
  if (value.type === 'draft-selection') return integer(value.season) && owner(value.owner) && typeof value.player_id === 'string' && value.player_id.length > 0;
  if (value.type === 'transaction') return integer(value.season) && typeof value.transaction_id === 'string' && value.transaction_id.length > 0;
  if (value.type === 'season') return integer(value.season);
  if (value.type === 'record') return value.selector === 'lowest-score' && anchor(value.game);
  if (value.type === 'rivalry') return Array.isArray(value.owners) && value.owners.length === 2 && value.owners.every(owner);
  return false;
};
const entry = (value: unknown) => object(value) && id(value.id) && strings(value.body) && strings(value.owners) && arrayOf(value.anchors, anchor) && strings(value.search_terms)
  && typeof value.category === 'string' && typeof value.title === 'string' && typeof value.teaser === 'string' && typeof value.provenance === 'string'
  && [value.season, value.occurred_year, value.completed_year, value.almanac_edition].every(item => item === null || integer(item))
  && ['ordinary', 'sensitive', 'respectful'].includes(value.sensitivity) && typeof value.enabled === 'boolean';
const trigger = (value: unknown) => object(value) && id(value.id) && typeof value.surface === 'string' && typeof value.activation === 'string'
  && typeof value.once_policy === 'string' && typeof value.enabled === 'boolean'
  && (('entry_id' in value) !== ('collection_id' in value)) && (!('effect_id' in value) || id(value.effect_id));
const collection = (value: unknown) => object(value) && id(value.id) && typeof value.title === 'string' && typeof value.summary === 'string' && Array.isArray(value.entry_ids) && value.entry_ids.length > 0 && strings(value.entry_ids) && strings(value.search_terms) && typeof value.enabled === 'boolean';
const effect = (value: unknown) => object(value) && id(value.id) && typeof value.label === 'string' && typeof value.symbol === 'string' && typeof value.presentation === 'string' && typeof value.tone === 'string' && integer(value.duration_ms) && typeof value.motion_policy === 'string' && typeof value.enabled === 'boolean';
export function isLeagueLore(value: unknown): value is LeagueLore {
  return object(value) && value.schema_version === 1 && typeof value.enabled === 'boolean' && typeof value.updated_at === 'string'
    && object(value.source_policy) && strings(value.source_policy.numeric_authority) && integer(value.source_policy.almanac_narrative_through)
    && arrayOf(value.owners, item => object(item) && owner(item.owner) && strings(item.aliases))
    && arrayOf(value.commissioner_terms, item => object(item) && id(item.id) && owner(item.owner) && integer(item.term_start) && (item.term_end === null || integer(item.term_end)) && typeof item.display_term === 'string' && typeof item.summary === 'string' && strings(item.entry_ids))
    && arrayOf(value.collections, collection) && arrayOf(value.effects, effect) && arrayOf(value.entries, entry) && arrayOf(value.triggers, trigger);
}
`;
  fs.mkdirSync(path.dirname(loreOutputPath), { recursive: true });
  fs.writeFileSync(loreOutputPath, `// This file is generated by scripts/generate_asset_validators.cjs. Do not edit manually.\n// @ts-nocheck\n${loreValidator.trim()}\n`);

  const transactionStandaloneModule = specializeFormatRuntime(compactValidatorErrors(standaloneCode(ajv, {
    validateTransactionHistory: schemaId('transaction-history.schema.json'),
  })));
  const transactionModuleCode = esbuild.buildSync({
    stdin: {
      contents: transactionStandaloneModule,
      loader: 'js',
      resolveDir: sourceRoot,
      sourcefile: 'transaction-history-validator-runtime.mjs',
    },
    bundle: true,
    platform: 'browser',
    format: 'esm',
    target: 'es2022',
    write: false,
    legalComments: 'none',
  }).outputFiles[0].text;
  const transactionWrappers = `

import type { TransactionHistory } from './asset-types';

export function isTransactionHistory(value: unknown): value is TransactionHistory { return validateTransactionHistory(value) as boolean; }
export function getTransactionHistoryValidatorErrors(): Array<{ instancePath?: string; message?: string }> | null {
  return (validateTransactionHistory as any).errors || null;
}
`;
  const transactionOutputPath = path.join(outputRoot, GENERATED_ASSETS.TransactionHistoryValidator.path);
  fs.mkdirSync(path.dirname(transactionOutputPath), { recursive: true });
  fs.writeFileSync(
    transactionOutputPath,
    `// This file is generated by scripts/generate_asset_validators.cjs. Do not edit manually.\n// @ts-nocheck\n${transactionModuleCode.trim()}${transactionWrappers}`,
  );
  return outputPath;
}

if (require.main === module) {
  try {
    const output = generateAssetValidators({ outputRoot: outputRootFromArgs(process.argv.slice(2)) });
    console.log(`Generated ${path.relative(process.cwd(), output)}`);
  } catch (error) {
    console.error(error.message || error);
    process.exit(1);
  }
}

module.exports = {
  generateAssetValidators,
  compactValidatorErrors,
  outputRootFromArgs,
  specializeFormatRuntime,
};
